### ISSUE TITLE
No sync/resync button

### ISSUE THREAD

**Issue by nolan-interactive** [plesk/ext-slave-dns-manager#25]
There is no sync or resync button.

Plesk Windows 12.0.18 Update #79
Slave DNS Manager (latest)

**Comment by vlikhtanskiy** [comment]
This button is available only for Plesk Onyx because resync backend was introduced in that version.

**Comment by ayamshanov** [comment]
I close the issue because it is not a bug, it is a limitation of Plesk 12.x. I suggest updating Plesk to get 'Resync" button.
