### ISSUE TITLE
Broken on Obsidian.

### ISSUE THREAD

**Issue by agarzon** [plesk/ext-slave-dns-manager#36]
The icon status is just broken after upgrading to Obsidian.  

Confirmed with different servers, same problem in all of them.

![screen](https://i.imgur.com/CbLimoF.png)

**Comment by jfkeegan** [comment]
There are numerous issues with missing images for extensions in Obsidian. try this:

```
cd /usr/local/psa/admin/htdocs
ln -s /usr/local/psa/admin/cp/public/theme theme

```

**Comment by ayamshanov** [comment]
Thank you for your bug report. The bug is confirmed as EXTPLESK-1403.
